version: '2'

services:
  nginx:
    environment:
      TZ: Asia/Tokyo
    build: ./containers
    volumes:
      - ./log/nginx/:/var/log/nginx/
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    hostname: nginx
    ports: 
      - 8100:80
