version: '2'

services:
  wekan:
    container_name: wekan
    image: mquandalle/wekan
    hostname: wekan
    links:
      - wekan_db
    restart: always
    environment:
      - MONGO_URL=mongodb://wekan_db/wekan
      - ROOT_URL=http://<接続先>:8081
    ports:
      - 8081:80
    networks:
      vpc:
        ipv4_address: 172.18.0.10

  wekan_db:
    container_name: wekan_db
    image: mongo
    hostname: wekan_db
    restart: always
    volumes:
      - /home/wekan/data:/data/db
    networks:
      vpc:
        ipv4_address: 172.18.0.11

networks:
  vpc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
