wekan:
   image: mquandalle/wekan
   restart: always
   links:
     - wekandb
   environment:
     - MONGO_URL=mongodb://wekandb/wekan
     - ROOT_URL=http://<domain_name>:8081
   ports:
     - 8081:80

 wekandb:
   image: mongo
   volumes:
     - /home/wekan/data:/data/db





























